### ISSUE TITLE
Component Argument Type Error

### ISSUE THREAD

**Issue by enoxaiming** [Y-Scholars/db.kscy.org_Front#1]
Error In ../db.kscy.org/src/app/components/header/header.component.ts (20,5): Argument of type '{ selector: string; template: string; directives: typeof Login[]; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.)

**Comment by jacepark12** [comment]
@dudgns0507 고쳐주세염
