### ISSUE TITLE
Search Layout 

### ISSUE THREAD

**Issue by jacepark12** [Y-Scholars/db.kscy.org_Front#3]
@dudgns0507 @enoxaiming 
검색 페이지가 원래 이렇게 나오는건가여??!1

<img width="1396" alt="2017-05-16 10 07 05" src="https://cloud.githubusercontent.com/assets/11798004/26085474/8ac2e076-3a1f-11e7-99c5-de2507c4e91a.png">

**Comment by enoxaiming** [comment]
수정하다가 잘못 건드린듯 ㅠㅠ 수정함!
