### ISSUE TITLE
dist_produce.py upload issue

### ISSUE THREAD

**Issue by enoxaiming** [Y-Scholars/db.kscy.org_Front#6]
dist_produce 파일을 통해 서버에 업로드 할때, assets 폴더 안에 있는 파일들이 그냥 dist 디렉토리에 저장이 되어서 db.kscy.org 에서 사진을 불러오지 못함.

원래 사용하고 있던 angular-cli 버전에서는 강제적으로 파일 경로를 지정해주었지만, angular-cli 최신버전에서는 아예 빌드가 불가능함.

이 부분만 해결되면, 이미지 관련 이슈는 전부 처리된 듯.

혹시 이해가 안될 수 있어서 사진도 첨부함.
<img width="562" alt="2017-06-16 10 48 46" src="https://user-images.githubusercontent.com/18255656/27229286-02759364-52e6-11e7-8013-23f0c49e79b9.png">
dist 폴더 안에 assets 폴더가 존재하지만,

<img width="483" alt="2017-06-16 10 49 31" src="https://user-images.githubusercontent.com/18255656/27229316-14dd47ae-52e6-11e7-8819-e301bd97a029.png">
서버에서 확인할 때는 파일만 존재함.

부탁드림다 :)

@pRivAte12  @dudgns0507

**Comment by jacepark12** [comment]
오케이 집가서 빨리 확인해볼께
